baseURL: "https://blairshevlin.github.io" 
title: Blair Shevlin
paginate: 20
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true

taxonomies:
    tag: tags

menu:
    main:
        - name: Papers
          url: papers/
          weight: 1
        - name: Courses
          url: courses/
          weight: 2
        - name: Data
          url: data/
          weight: 3 

params:
    description: "I am Blair Shevlin, a Postdoctoral Researcher at the Center for Computational Psychiatry hosted at the Icahn School of Medicine at Mount Sinai. My research covers decision-making, computational modeling, and psychiatry."
    author: Name
    # googleAnalyticsID: "G-XXXXX"
    DateFormat: "January 2006"
    defaultTheme: light
    hideFooter: false
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowRssButtonInSectionTermList: false
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: Blair Shevlin, PhD
          subtitle: "I am a Postdoctoral Researcher at the Center for Computational Psychiatry. I work on various topics related to decision-making, computational modeling, and psychiatry."
          imageUrl: "picture.jpeg"
          imageWidth: 160
          imageHeight: 160
          imageTitle: Blair Shevlin
          buttons:
            - name: Papers
              url: papers/
            - name: Courses
              url: courses/
            - name: Data
              url: data/
            - name: Tags
              url: tags/
            - name: Archive
              url: archive/
    socialIcons:
        - name: CV
          url: cv.pdf
        - name: Email
          url: mailto:blairshevlin@gmail.com
        - name: Location
          url: Center for Computational Psychiatry, Icahn School of Medicine, New York, NY
        - name: Google Scholar
          url: https://scholar.google.com/citations?user=J_t6LicAAAAJ
        - name: GitHub
          url: https://github.com/blairshevlin
        - name: Twitter
          url: https://twitter.com/blairshevlin

    assets:
        disableHLJS: true
        disableScrollBarStyle: true
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
      text: "Blair Shevlin"
      icon: favicon.ico
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2
